services:
  - type: web
    name: cabo
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        generateValue: true
